# Generated by Django 5.0.3 on 2024-06-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menuitem_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectionsection',
            name='items',
        ),
        migrations.AddField(
            model_name='menusection',
            name='type',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.DeleteModel(
            name='SelectionItem',
        ),
        migrations.DeleteModel(
            name='SelectionSection',
        ),
    ]
