# Generated by Django 5.0.3 on 2024-06-05 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_remove_selectionsection_items_menusection_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='menu.menusection'),
        ),
    ]
