# Generated by Django 5.0.3 on 2024-06-05 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_note_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_notes', to='menu.menusection'),
        ),
    ]
